const PDFDocument = require("pdfkit");

const generateInvoice = (payment, res) => {
    const doc = new PDFDocument();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
        "Content-Disposition",
        `attachment; filename=invoice-${payment._id}.pdf`
    );

    doc.pipe(res);

    doc.fontSize(22).text("UNFAZED", { align: "center" });

    doc.moveDown();

    doc.fontSize(16).text("Payment Invoice", {
        align: "center"
    });

    doc.moveDown(2);

    doc.fontSize(12);

    doc.text(`Invoice ID: ${payment._id}`);
    doc.text(`Date: ${new Date(payment.createdAt).toLocaleDateString()}`);

    doc.moveDown();

    doc.text(`Client Name: ${payment.clientName}`);
    doc.text(`Client Email: ${payment.clientEmail}`);

    doc.moveDown();

    doc.text(`Package ID: ${payment.packageId}`);

    doc.moveDown();

    doc.text(`Amount: Rs. ${payment.amount}`);
     const platformFee = payment.platformFee || 0;
const netAmount = payment.netAmount || payment.amount - platformFee;

doc.text(`Platform Fee: Rs. ${platformFee}`);
doc.text(`Net Amount: Rs. ${netAmount}`);

    doc.moveDown();

    doc.text(`Payment Status: ${payment.status}`);

    doc.moveDown(2);

    doc.text("GST-style Invoice", {
        align: "center"
    });

    doc.moveDown();

    doc.text(
        "This invoice is generated by the Unfazed therapy platform."
    );

    doc.end();
};

module.exports = generateInvoice;